<?php

use App\Actions\ContactSubmissions\AddContactSubmissionNote;
use App\Actions\ContactSubmissions\ChangeContactSubmissionWorkflow;
use App\Actions\ContactSubmissions\DeleteContactSubmission;
use App\ContactSubmissionPriority;
use App\ContactSubmissionStatus;
use App\Models\ContactSubmission;
use App\Models\User;
use Flux\Flux;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Livewire\Attributes\Computed;
use Livewire\Attributes\Title;
use Livewire\Component;

new #[Title('Contact Submission')] class extends Component
{
    public ContactSubmission $contactSubmission;
    public string $status = '';
    public string $priority = '';
    public int|string|null $assignedTo = null;
    public string $note = '';

    public function mount(ContactSubmission $contactSubmission, ChangeContactSubmissionWorkflow $workflow): void
    {
        Gate::authorize('view', $contactSubmission); abort_if($contactSubmission->trashed(), 404); $this->contactSubmission = $contactSubmission;
        $this->contactSubmission = $workflow->markRead(Auth::user(), $contactSubmission);
        $this->status = $this->contactSubmission->status->value; $this->priority = $this->contactSubmission->priority->value; $this->assignedTo = $this->contactSubmission->assigned_to; $this->refreshSubmission();
    }

    #[Computed] public function assignees() { return User::query()->where('account_status', 'active')->permission('contact-submissions.update')->orderBy('name')->get(['id', 'name']); }
    public function updateStatus(ChangeContactSubmissionWorkflow $workflow): void { $this->contactSubmission = $workflow->changeStatus(Auth::user(), $this->contactSubmission, ContactSubmissionStatus::from($this->status)); $this->refreshSubmission(); Flux::toast(variant: 'success', text: __('Status updated.')); }
    public function updatePriority(ChangeContactSubmissionWorkflow $workflow): void { $this->contactSubmission = $workflow->changePriority(Auth::user(), $this->contactSubmission, ContactSubmissionPriority::from($this->priority)); $this->refreshSubmission(); Flux::toast(variant: 'success', text: __('Priority updated.')); }
    public function updateAssignment(ChangeContactSubmissionWorkflow $workflow): void { $this->contactSubmission = $workflow->assign(Auth::user(), $this->contactSubmission, filled($this->assignedTo) ? User::findOrFail((int) $this->assignedTo) : null); $this->refreshSubmission(); Flux::toast(variant: 'success', text: __('Assignment updated.')); }
    public function markUnread(ChangeContactSubmissionWorkflow $workflow): void { $this->contactSubmission = $workflow->markUnread(Auth::user(), $this->contactSubmission); $this->refreshSubmission(); }
    public function recordReply(ChangeContactSubmissionWorkflow $workflow): void { $this->contactSubmission = $workflow->recordReply(Auth::user(), $this->contactSubmission); $this->status = $this->contactSubmission->status->value; $this->refreshSubmission(); Flux::toast(variant: 'success', text: __('Reply recorded.')); }
    public function addNote(AddContactSubmissionNote $action): void { $this->validate(['note' => ['required', 'string', 'min:3', 'max:10000']]); $action->handle(Auth::user(), $this->contactSubmission, $this->note); $this->reset('note'); $this->resetValidation(); $this->refreshSubmission(); Flux::toast(variant: 'success', text: __('Internal note added.')); }
    public function delete(DeleteContactSubmission $action): void { $action->delete(Auth::user(), $this->contactSubmission); session()->flash('success', __('Contact submission moved to trash.')); $this->redirectRoute('contact-submissions.index', navigate: true); }
    public function emailReplyUrl(): string { return 'mailto:'.$this->contactSubmission->email.'?subject='.rawurlencode($this->contactSubmission->replySubject()); }
    private function refreshSubmission(): void { $this->contactSubmission = $this->contactSubmission->refresh()->load(['assignedUser:id,name,email', 'resolvedByUser:id,name', 'notes.user:id,name']); }
};
?>

<div class="mx-auto w-full max-w-[100rem] space-y-6"><flux:breadcrumbs><flux:breadcrumbs.item :href="route('dashboard')" wire:navigate>{{ __('Dashboard') }}</flux:breadcrumbs.item><flux:breadcrumbs.item :href="route('contact-submissions.index')" wire:navigate>{{ __('Contact submissions') }}</flux:breadcrumbs.item><flux:breadcrumbs.item>{{ $contactSubmission->reference_number }}</flux:breadcrumbs.item></flux:breadcrumbs>
<x-admin.page-header :title="$contactSubmission->subject" :description="$contactSubmission->reference_number" :eyebrow="__('Contact enquiry')"><x-slot:actions>@can('update', $contactSubmission)<flux:button wire:click="markUnread" icon="envelope">{{ __('Mark unread') }}</flux:button>@endcan @can('reply', $contactSubmission)<flux:button :href="$this->emailReplyUrl()" icon="paper-airplane">{{ __('Open email reply') }}</flux:button><flux:button wire:click="recordReply" wire:confirm="{{ __('Confirm that a reply was sent?') }}" variant="primary">{{ __('Record reply sent') }}</flux:button>@endcan @can('delete', $contactSubmission)<flux:button wire:click="delete" wire:confirm="{{ __('Move this submission to trash?') }}" variant="danger" icon="trash">{{ __('Delete') }}</flux:button>@endcan</x-slot:actions></x-admin.page-header>
<div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_24rem]"><div class="space-y-6"><section class="rounded-xl border border-slate-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"><div class="flex flex-wrap gap-2"><flux:badge :color="$contactSubmission->status->color()">{{ $contactSubmission->status->label() }}</flux:badge><flux:badge :color="$contactSubmission->priority->color()">{{ $contactSubmission->priority->label() }}</flux:badge><flux:badge>{{ $contactSubmission->category->label() }}</flux:badge></div><flux:heading size="lg" class="mt-6">{{ __('Message') }}</flux:heading><div class="mt-4 whitespace-pre-line leading-7">{{ $contactSubmission->message }}</div></section>
<section class="rounded-xl border border-slate-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"><flux:heading>{{ __('Visitor details') }}</flux:heading><dl class="mt-5 grid gap-5 sm:grid-cols-2"><div><dt class="text-sm text-slate-500">{{ __('Name') }}</dt><dd class="font-medium">{{ $contactSubmission->name }}</dd></div><div><dt class="text-sm text-slate-500">{{ __('Email') }}</dt><dd class="break-all"><a class="text-church-maroon-700 hover:underline dark:text-church-gold-400" href="mailto:{{ $contactSubmission->email }}">{{ $contactSubmission->email }}</a> <button type="button" class="ms-2 text-xs underline" data-copy-text="{{ $contactSubmission->email }}">{{ __('Copy') }}</button></dd></div><div><dt class="text-sm text-slate-500">{{ __('Phone') }}</dt><dd>{{ $contactSubmission->phone ?: '—' }}</dd></div><div><dt class="text-sm text-slate-500">{{ __('Preferred contact') }}</dt><dd>{{ $contactSubmission->preferred_contact_method->label() }}</dd></div></dl></section>
<section class="rounded-xl border border-slate-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"><flux:heading>{{ __('Internal notes') }}</flux:heading><div class="mt-5 space-y-4">@forelse($contactSubmission->notes as $item)<article class="border-l-2 border-church-gold-500 pl-4" wire:key="contact-note-{{ $item->id }}"><div class="flex justify-between gap-4"><p class="font-semibold">{{ $item->user?->name ?? __('Former administrator') }}</p><time class="text-xs text-slate-500">{{ $item->created_at?->format('M j, Y g:i A') }}</time></div><p class="mt-2 whitespace-pre-line text-sm">{{ $item->note }}</p></article>@empty<p class="text-sm text-slate-500">{{ __('No internal notes yet.') }}</p>@endforelse</div>@can('addNote', $contactSubmission)<form wire:submit="addNote" class="mt-6 space-y-3"><flux:textarea wire:model="note" :label="__('Add an internal note')" rows="4"/><div class="text-right"><flux:button type="submit" variant="primary" wire:loading.attr="disabled" wire:target="addNote">{{ __('Add note') }}</flux:button></div></form>@endcan</section></div>
<aside class="space-y-6"><section class="space-y-4 rounded-xl border border-slate-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><flux:heading>{{ __('Management') }}</flux:heading>@can('update', $contactSubmission)<flux:select wire:model="status" wire:change="updateStatus" :label="__('Status')">@foreach(ContactSubmissionStatus::cases() as $item)@if(($item !== ContactSubmissionStatus::Resolved || Gate::allows('resolve', $contactSubmission)) && ($item !== ContactSubmissionStatus::Spam || Gate::allows('markSpam', $contactSubmission)))<flux:select.option :value="$item->value">{{ $item->label() }}</flux:select.option>@endif @endforeach</flux:select><flux:select wire:model="priority" wire:change="updatePriority" :label="__('Priority')">@foreach(ContactSubmissionPriority::cases() as $item)<flux:select.option :value="$item->value">{{ $item->label() }}</flux:select.option>@endforeach</flux:select>@endcan @can('assign', $contactSubmission)<flux:select wire:model="assignedTo" wire:change="updateAssignment" :label="__('Assigned administrator')"><flux:select.option value="">{{ __('Unassigned') }}</flux:select.option>@foreach($this->assignees as $user)<flux:select.option :value="$user->id">{{ $user->name }}</flux:select.option>@endforeach</flux:select>@endcan</section>
<section class="rounded-xl border border-slate-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><flux:heading>{{ __('Record history') }}</flux:heading><dl class="mt-4 space-y-3 text-sm">@foreach([__('Received') => $contactSubmission->created_at?->format('M j, Y g:i A'), __('First read') => $contactSubmission->read_at?->format('M j, Y g:i A'), __('Reply recorded') => $contactSubmission->admin_replied_at?->format('M j, Y g:i A'), __('Resolved') => $contactSubmission->resolved_at?->format('M j, Y g:i A'), __('Resolved by') => $contactSubmission->resolvedByUser?->name, __('Assigned to') => $contactSubmission->assignedUser?->name] as $label => $value)<div><dt class="text-slate-500">{{ $label }}</dt><dd>{{ $value ?: '—' }}</dd></div>@endforeach</dl></section>
<details class="rounded-xl border border-slate-200 bg-white p-5 text-sm dark:border-zinc-800 dark:bg-zinc-900"><summary class="cursor-pointer font-semibold">{{ __('Technical metadata') }}</summary><dl class="mt-4 space-y-3"><div><dt class="text-slate-500">{{ __('Source page') }}</dt><dd class="break-words">{{ $contactSubmission->source_page ?: '—' }}</dd></div><div><dt class="text-slate-500">{{ __('IP address') }}</dt><dd>{{ $contactSubmission->ip_address ?: '—' }}</dd></div><div><dt class="text-slate-500">{{ __('User agent') }}</dt><dd class="break-words">{{ $contactSubmission->user_agent ?: '—' }}</dd></div></dl></details></aside></div></div>
