<?php
use App\Actions\Pages\DuplicatePage;
use App\Actions\Pages\ManagePage;
use App\Models\Page;
use App\PageStatus;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\URL as LaravelUrl;
use Livewire\Attributes\Computed;
use Livewire\Attributes\Layout;
use Livewire\Attributes\Url;
use Livewire\Component;
use Livewire\WithPagination;

new #[Layout('layouts.app')] class extends Component {
    use WithPagination;
    #[Url] public string $search=''; #[Url] public string $status=''; #[Url] public string $type=''; #[Url] public string $visibility=''; #[Url] public string $navigation=''; public array $selected=[];
    public function mount(): void { Gate::authorize('viewAny',Page::class); }
    public function updated(string $property): void { if (in_array($property,['search','status','type','visibility','navigation'],true)) { $this->resetPage(); } }
    #[Computed] public function pages() { return Page::query()->with(['parent:id,title','updater:id,name'])->when($this->search!=='',fn(Builder $q)=>$q->search($this->search))->when($this->status!=='',fn(Builder $q)=>$q->where('status',$this->status))->when($this->type!=='',fn(Builder $q)=>$q->where('page_type',$this->type))->when($this->visibility!=='',fn(Builder $q)=>$q->where('visibility',$this->visibility))->when($this->navigation!=='',fn(Builder $q)=>$q->where('show_in_navigation',$this->navigation==='1'))->latest('updated_at')->paginate(15); }
    #[Computed] public function stats(): array { return ['total'=>Page::count(),'published'=>Page::where('status','published')->count(),'draft'=>Page::where('status','draft')->count(),'scheduled'=>Page::where('status','scheduled')->count(),'archived'=>Page::where('status','archived')->count()]; }
    public function clearFilters(): void { $this->reset('search','status','type','visibility','navigation'); $this->resetPage(); }
    public function publish(int $id,ManagePage $action): void { $action->publish(auth()->user(),Page::findOrFail($id)); }
    public function unpublish(int $id,ManagePage $action): void { $action->unpublish(auth()->user(),Page::findOrFail($id)); }
    public function archive(int $id,ManagePage $action): void { $action->archive(auth()->user(),Page::findOrFail($id)); }
    public function delete(int $id,ManagePage $action): void { $action->delete(auth()->user(),Page::findOrFail($id)); }
    public function duplicate(int $id,DuplicatePage $action): void { $copy=$action->handle(auth()->user(),Page::with('sections')->findOrFail($id)); $this->redirectRoute('pages.edit',$copy,navigate:true); }
    public function preview(int $id): void { $page=Page::findOrFail($id); Gate::authorize('preview',$page); $this->redirect(LaravelUrl::temporarySignedRoute('pages.preview',now()->addMinutes(30),['page'=>$page]),navigate:false); }
    public function bulk(string $operation,ManagePage $action): void { foreach(Page::query()->whereKey($this->selected)->get() as $page){ if($operation==='publish'){$action->publish(auth()->user(),$page);} elseif($operation==='archive'){$action->archive(auth()->user(),$page);} elseif($operation==='delete'){$action->delete(auth()->user(),$page);} } $this->selected=[]; }
}; ?>
<main id="admin-main" class="p-4 sm:p-6 lg:p-8"><div class="mx-auto max-w-7xl space-y-6">
<x-admin.page-header :title="__('Pages')" :description="__('Manage public page content, publication, navigation, sections, and search metadata.')"><x-slot:actions>@can(\App\PermissionName::PagesRestore->value)<flux:button :href="route('pages.trash')" wire:navigate icon="trash">{{ __('Trash') }}</flux:button>@endcan @can(\App\PermissionName::PagesCreate->value)<flux:button :href="route('pages.create')" wire:navigate variant="primary" icon="plus">{{ __('Create page') }}</flux:button>@endcan</x-slot:actions></x-admin.page-header>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">@foreach(['total'=>'Total pages','published'=>'Published','draft'=>'Drafts','scheduled'=>'Scheduled','archived'=>'Archived'] as $key=>$label)<x-admin.stat-card :label="__($label)" :value="$this->stats[$key]" :caption="__('Current page count')" icon="document-text" />@endforeach</div>
<flux:card><div class="grid gap-3 md:grid-cols-2 xl:grid-cols-6"><flux:input wire:model.live.debounce.350ms="search" icon="magnifying-glass" :placeholder="__('Search pages…')" class="xl:col-span-2" /><flux:select wire:model.live="status"><flux:select.option value="">{{ __('All statuses') }}</flux:select.option>@foreach(\App\PageStatus::cases() as $item)<flux:select.option :value="$item->value">{{ $item->label() }}</flux:select.option>@endforeach</flux:select><flux:select wire:model.live="type"><flux:select.option value="">{{ __('All types') }}</flux:select.option>@foreach(\App\PageType::cases() as $item)<flux:select.option :value="$item->value">{{ $item->label() }}</flux:select.option>@endforeach</flux:select><flux:select wire:model.live="visibility"><flux:select.option value="">{{ __('All visibility') }}</flux:select.option>@foreach(\App\PageVisibility::cases() as $item)<flux:select.option :value="$item->value">{{ $item->label() }}</flux:select.option>@endforeach</flux:select><flux:button wire:click="clearFilters">{{ __('Clear') }}</flux:button></div></flux:card>
@if($selected)<div class="flex flex-wrap items-center gap-2 rounded-xl bg-church-maroon-50 p-3 dark:bg-zinc-900"><span class="text-sm font-medium">{{ count($selected) }} {{ __('selected') }}</span>@can(\App\PermissionName::PagesPublish->value)<flux:button size="sm" wire:click="bulk('publish')">{{ __('Publish') }}</flux:button><flux:button size="sm" wire:click="bulk('archive')">{{ __('Archive') }}</flux:button>@endcan @can(\App\PermissionName::PagesDelete->value)<flux:button size="sm" variant="danger" wire:click="bulk('delete')" wire:confirm="{{ __('Delete selected pages?') }}">{{ __('Delete') }}</flux:button>@endcan</div>@endif
<flux:card class="overflow-x-auto p-0"><flux:table :paginate="$this->pages"><flux:table.columns><flux:table.column></flux:table.column><flux:table.column>{{ __('Page') }}</flux:table.column><flux:table.column>{{ __('Type') }}</flux:table.column><flux:table.column>{{ __('Status') }}</flux:table.column><flux:table.column>{{ __('Visibility') }}</flux:table.column><flux:table.column>{{ __('Updated') }}</flux:table.column><flux:table.column></flux:table.column></flux:table.columns><flux:table.rows>
@forelse($this->pages as $page)<flux:table.row wire:key="page-{{ $page->id }}"><flux:table.cell><flux:checkbox wire:model.live="selected" :value="$page->id" aria-label="{{ __('Select :title',['title'=>$page->title]) }}" /></flux:table.cell><flux:table.cell><div class="font-semibold">{{ $page->title }} @if($page->is_homepage)<flux:badge size="sm" color="amber">{{ __('Homepage') }}</flux:badge>@endif</div><div class="text-xs text-slate-500">/{{ $page->slug }} @if($page->parent) · {{ __('Child of :page',['page'=>$page->parent->title]) }}@endif</div></flux:table.cell><flux:table.cell>{{ $page->page_type->label() }}</flux:table.cell><flux:table.cell><flux:badge size="sm">{{ $page->status->label() }}</flux:badge></flux:table.cell><flux:table.cell>{{ $page->visibility->label() }}</flux:table.cell><flux:table.cell><div>{{ $page->updated_at->diffForHumans() }}</div><div class="text-xs text-slate-500">{{ $page->updater?->name }}</div></flux:table.cell><flux:table.cell><flux:dropdown><flux:button icon="ellipsis-horizontal" variant="ghost" aria-label="{{ __('Page actions') }}" /><flux:menu>@can('update',$page)<flux:menu.item :href="route('pages.edit',$page)" wire:navigate icon="pencil-square">{{ __('Edit') }}</flux:menu.item>@endcan @can('manageSections',$page)<flux:menu.item :href="route('pages.sections',$page)" wire:navigate icon="rectangle-stack">{{ __('Sections') }}</flux:menu.item>@endcan @can('preview',$page)<flux:menu.item wire:click="preview({{ $page->id }})" icon="eye">{{ __('Preview') }}</flux:menu.item>@endcan @can('duplicate',$page)<flux:menu.item wire:click="duplicate({{ $page->id }})" icon="document-duplicate">{{ __('Duplicate') }}</flux:menu.item>@endcan @can('publish',$page)@if($page->status===PageStatus::Published)<flux:menu.item wire:click="unpublish({{ $page->id }})">{{ __('Unpublish') }}</flux:menu.item>@else<flux:menu.item wire:click="publish({{ $page->id }})">{{ __('Publish') }}</flux:menu.item>@endif<flux:menu.item wire:click="archive({{ $page->id }})">{{ __('Archive') }}</flux:menu.item>@endcan @can('delete',$page)<flux:menu.separator/><flux:menu.item wire:click="delete({{ $page->id }})" wire:confirm="{{ __('Move this page to trash?') }}" variant="danger">{{ __('Delete') }}</flux:menu.item>@endcan</flux:menu></flux:dropdown></flux:table.cell></flux:table.row>
@empty<flux:table.row><flux:table.cell colspan="7"><x-admin.empty-state icon="document-text" :title="__('No pages found')" :description="__('Create a page or change the current filters.')" /></flux:table.cell></flux:table.row>@endforelse
</flux:table.rows></flux:table></flux:card></div></main>
