<?php
use App\Activity\ActivityLogger;
use App\Blog\HtmlSanitizer;
use App\Models\Page;
use App\Models\PageSection;
use App\PageSectionType;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\ValidationException;
use Illuminate\Validation\Rule;
use Livewire\Attributes\Layout;
use Livewire\Component;

new #[Layout('layouts.app')] class extends Component {
    public Page $page; public ?int $sectionId=null; public string $sectionType='rich-text'; public string $name=''; public string $heading=''; public string $subheading=''; public string $content=''; public string $settings='{}'; public bool $isVisible=true;
    public function mount(Page $page): void { Gate::authorize('manageSections',$page); $this->page=$page->load(['sections.backgroundImage']); }
    public function edit(int $id): void { Gate::authorize('manageSections',$this->page); $section=$this->page->sections()->findOrFail($id); $this->sectionId=$section->id; $this->sectionType=$section->section_type->value; $this->name=$section->name; $this->heading=$section->heading??''; $this->subheading=$section->subheading??''; $this->content=$section->content??''; $this->settings=json_encode($section->settings??[],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES); $this->isVisible=$section->is_visible; }
    public function save(HtmlSanitizer $sanitizer,ActivityLogger $logger): void { Gate::authorize('manageSections',$this->page); $validated=$this->validate(['sectionType'=>['required',Rule::enum(PageSectionType::class)],'name'=>['required','string','max:255'],'heading'=>['nullable','string','max:255'],'subheading'=>['nullable','string','max:255'],'content'=>['nullable','string','max:200000'],'settings'=>['required','json'],'isVisible'=>['boolean']]); $settings=$this->validatedSettings($validated['sectionType'],$validated['settings']); $section=$this->sectionId?$this->page->sections()->findOrFail($this->sectionId):new PageSection(['page_id'=>$this->page->id,'sort_order'=>(int)$this->page->sections()->max('sort_order')+1,'created_by'=>auth()->id()]); $event=$section->exists?'updated':'added'; $section->fill(['section_type'=>$validated['sectionType'],'name'=>$validated['name'],'heading'=>$validated['heading'],'subheading'=>$validated['subheading'],'content'=>$sanitizer->sanitize($validated['content']),'settings'=>$settings,'is_visible'=>$validated['isVisible'],'updated_by'=>auth()->id()])->save(); $logger->log('pages','page-section.'.$event,str($event)->headline().' section "'.$section->name.'".',$this->page,auth()->user(),properties:['section_id'=>$section->id]); $this->resetForm(); $this->page->load('sections'); }
    public function toggle(int $id,ActivityLogger $logger): void { Gate::authorize('manageSections',$this->page); $section=$this->page->sections()->findOrFail($id); $section->update(['is_visible'=>!$section->is_visible,'updated_by'=>auth()->id()]); $logger->log('pages','page-section.toggled','Changed section visibility.',$this->page,auth()->user(),properties:['section_id'=>$section->id,'is_visible'=>$section->is_visible]); $this->page->load('sections'); }
    public function move(int $id,string $direction,ActivityLogger $logger): void { Gate::authorize('manageSections',$this->page); $section=$this->page->sections()->findOrFail($id); $operator=$direction==='up'?'<': '>'; $order=$direction==='up'?'desc':'asc'; $other=$this->page->sections()->where('sort_order',$operator,$section->sort_order)->orderBy('sort_order',$order)->first(); if(!$other){return;} DB::transaction(function()use($section,$other){[$section->sort_order,$other->sort_order]=[$other->sort_order,$section->sort_order];$section->save();$other->save();}); $logger->log('pages','page-section.reordered','Reordered page sections.',$this->page,auth()->user()); $this->page->load('sections'); }
    public function duplicate(int $id): void { Gate::authorize('manageSections',$this->page); $section=$this->page->sections()->findOrFail($id); $copy=$section->replicate();$copy->name=$section->name.' (Copy)';$copy->sort_order=(int)$this->page->sections()->max('sort_order')+1;$copy->created_by=auth()->id();$copy->updated_by=auth()->id();$copy->save();$this->page->load('sections'); }
    public function delete(int $id): void { Gate::authorize('manageSections',$this->page); $this->page->sections()->findOrFail($id)->delete(); $this->page->load('sections'); }
    public function resetForm(): void { $this->reset('sectionId','name','heading','subheading','content');$this->sectionType='rich-text';$this->settings='{}';$this->isVisible=true; }
    private function validatedSettings(string $type,string $json): array { $settings=json_decode($json,true,512,JSON_THROW_ON_ERROR); $rules=match($type){'hero'=>['primary_label'=>['nullable','string','max:100'],'primary_url'=>['nullable','string','max:2048'],'secondary_label'=>['nullable','string','max:100'],'secondary_url'=>['nullable','string','max:2048'],'eyebrow'=>['nullable','string','max:150'],'overlay'=>['nullable','integer','between:0,100'],'alignment'=>['nullable',Rule::in(['left','center','right'])]],'featured-sermons','upcoming-events','latest-posts','ministries-grid','leadership-grid','books-grid'=>['limit'=>['nullable','integer','between:1,24'],'sort'=>['nullable',Rule::in(['latest','oldest','featured','manual'])],'category_id'=>['nullable','integer'],'series_id'=>['nullable','integer'],'speaker_id'=>['nullable','integer'],'show_view_all'=>['nullable','boolean']],'call-to-action','donation-callout','prayer-request-callout'=>['button_label'=>['nullable','string','max:100'],'url'=>['nullable','string','max:2048']],default=>[]}; $unknown=array_diff(array_keys($settings),array_keys($rules)); if($unknown!==[]){throw ValidationException::withMessages(['settings'=>__('Unsupported setting: :setting',['setting'=>reset($unknown)])]);} return Validator::make($settings,$rules)->validate(); }
}; ?>
<main id="admin-main" class="p-4 sm:p-6 lg:p-8"><div class="mx-auto max-w-7xl space-y-6"><x-admin.page-header :title="__('Sections: :page',['page'=>$page->title])" :description="__('Add, configure, hide, duplicate, and reorder approved section types.')"><x-slot:actions><flux:button :href="route('pages.edit',$page)" wire:navigate>{{ __('Back to page') }}</flux:button></x-slot:actions></x-admin.page-header>
<div class="grid gap-6 xl:grid-cols-[minmax(0,1.4fr)_minmax(22rem,1fr)]"><div class="space-y-3">@forelse($page->sections as $section)<flux:card wire:key="section-{{ $section->id }}" class="flex flex-col gap-3 sm:flex-row sm:items-center"><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><flux:heading>{{ $section->name }}</flux:heading><flux:badge size="sm">{{ $section->section_type->label() }}</flux:badge>@unless($section->is_visible)<flux:badge size="sm" color="zinc">{{ __('Hidden') }}</flux:badge>@endunless</div><p class="mt-1 truncate text-sm text-slate-500">{{ $section->heading }}</p></div><div class="flex flex-wrap gap-2"><flux:button size="sm" icon="arrow-up" wire:click="move({{ $section->id }},'up')" aria-label="{{ __('Move up') }}"/><flux:button size="sm" icon="arrow-down" wire:click="move({{ $section->id }},'down')" aria-label="{{ __('Move down') }}"/><flux:button size="sm" wire:click="toggle({{ $section->id }})">{{ $section->is_visible?__('Hide'):__('Show') }}</flux:button><flux:button size="sm" wire:click="duplicate({{ $section->id }})" icon="document-duplicate"/><flux:button size="sm" wire:click="edit({{ $section->id }})" icon="pencil"/><flux:button size="sm" variant="danger" wire:click="delete({{ $section->id }})" wire:confirm="{{ __('Delete this section?') }}" icon="trash"/></div></flux:card>@empty<x-admin.empty-state icon="rectangle-stack" :title="__('No sections yet')" :description="__('Add the first reusable section using the form.')"/>@endforelse</div>
<form wire:submit="save"><flux:card class="space-y-5"><flux:heading size="lg">{{ $sectionId?__('Edit section'):__('Add section') }}</flux:heading><flux:select wire:model.live="sectionType" :label="__('Section type')">@foreach(PageSectionType::cases() as $type)<flux:select.option :value="$type->value">{{ $type->label() }}</flux:select.option>@endforeach</flux:select><flux:input wire:model="name" :label="__('Internal name')" required/><flux:input wire:model="heading" :label="__('Heading')"/><flux:input wire:model="subheading" :label="__('Subheading')"/><flux:textarea wire:model="content" :label="__('Content')" rows="6"/><flux:textarea wire:model="settings" :label="__('Section settings (JSON)')" rows="9" class="font-mono text-sm" description="{{ __('Only validated JSON for the selected approved section type is stored.') }}"/><flux:switch wire:model="isVisible" :label="__('Visible')"/><div class="flex gap-2"><flux:button type="submit" variant="primary">{{ __('Save section') }}</flux:button>@if($sectionId)<flux:button type="button" wire:click="resetForm">{{ __('Cancel') }}</flux:button>@endif</div></flux:card></form></div></div></main>
