<?php
use App\Actions\Pages\ManagePage;
use App\Models\Page;
use Illuminate\Support\Facades\Gate;
use Livewire\Attributes\Computed;
use Livewire\Attributes\Layout;
use Livewire\Attributes\Url;
use Livewire\Component;
use Livewire\WithPagination;
new #[Layout('layouts.app')] class extends Component { use WithPagination; #[Url] public string $search=''; public function mount():void{Gate::authorize('viewAny',Page::class);abort_unless(auth()->user()->can(\App\PermissionName::PagesRestore),403);} #[Computed] public function pages(){return Page::onlyTrashed()->with('updater:id,name')->when($this->search!=='',fn($q)=>$q->search($this->search))->latest('deleted_at')->paginate(15);} public function restore(int $id,ManagePage $action):void{$action->restore(auth()->user(),Page::onlyTrashed()->findOrFail($id));} public function forceDelete(int $id,ManagePage $action):void{$action->forceDelete(auth()->user(),Page::onlyTrashed()->findOrFail($id));} }; ?>
<main id="admin-main" class="p-4 sm:p-6 lg:p-8"><div class="mx-auto max-w-6xl space-y-6"><x-admin.page-header :title="__('Page trash')" :description="__('Restore deleted pages or permanently remove eligible pages.')"><x-slot:actions><flux:button :href="route('pages.index')" wire:navigate>{{ __('Back to pages') }}</flux:button></x-slot:actions></x-admin.page-header><flux:input wire:model.live.debounce.350ms="search" icon="magnifying-glass" :placeholder="__('Search deleted pages…')"/><flux:card class="p-0"><flux:table :paginate="$this->pages"><flux:table.columns><flux:table.column>{{ __('Page') }}</flux:table.column><flux:table.column>{{ __('Deleted') }}</flux:table.column><flux:table.column></flux:table.column></flux:table.columns><flux:table.rows>@forelse($this->pages as $page)<flux:table.row wire:key="trash-page-{{ $page->id }}"><flux:table.cell><div class="font-semibold">{{ $page->title }}</div><div class="text-xs text-slate-500">/{{ $page->slug }}</div></flux:table.cell><flux:table.cell>{{ $page->deleted_at->diffForHumans() }}</flux:table.cell><flux:table.cell><div class="flex justify-end gap-2">@can('restore',$page)<flux:button size="sm" wire:click="restore({{ $page->id }})">{{ __('Restore') }}</flux:button>@endcan @can('forceDelete',$page)<flux:button size="sm" variant="danger" wire:click="forceDelete({{ $page->id }})" wire:confirm="{{ __('Permanently delete this page? This cannot be undone.') }}">{{ __('Delete forever') }}</flux:button>@endcan</div></flux:table.cell></flux:table.row>@empty<flux:table.row><flux:table.cell colspan="3"><x-admin.empty-state icon="trash" :title="__('Trash is empty')" :description="__('Deleted pages will appear here.')"/></flux:table.cell></flux:table.row>@endforelse</flux:table.rows></flux:table></flux:card></div></main>
